- name: Backend configuration
  hosts: backend
  become: true

  tasks:
    - name: Install Python and pip
      apt:
        name: [python3, python3-pip]
        state: present
    
    - name: copy files
      hosts: localhost
      connection: local
      tasks:
        - name: copy files backend 
          copy:
            src: /home/vagrant/chmury-w-aplikacjach/backend
            dest: /home/vagrant/chmury-w-aplikacjach/backend
           tags:
              - simple_copy
    
    - name: Install Python requirements
      pip:
        requirements: /home/vagrant/chmury-w-aplikacjach/backend/requirements.txt
        state: present

    - name: Start python app
      shell: |
        nohup python3 main.py > log.txt 2>&1 &
      args:
        chdir: /home/vagrant/chmury-w-aplikacjach/backend
      environment:
        DATABASE_LOCATION: 192.168.56.2