- name: Backend configuration
  hosts: backend
  become: true

  tasks:
    - name: Install Python and pip
      apt:
        name: [python3, python3-pip]
        state: present
    
    - name: Install Python requirements
      pip:
        requirements: /home/vagrant/chmury-w-aplikacjach/backend/requirements.txt
        state: present

    - name: Start python app
      shell: |
        nohup python3 main.py > log.txt 2>&1 &
      args:
        chdir: /home/vagrant/chmury-w-aplikacjach/backend
      environment:
        POSTGRES_HOSTNAME: 192.168.56.6
        DATABASE_PORT: 5432
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: admin
        POSTGRES_DB: people
        POSTGRES_HOST: postgres
        CSV_DATASET: /home/vagrant/chmury-w-aplikacjach/backend/Life_Expectancy_00_15.csv
        CLIENT_ORIGIN: http://192.168.56.3