---
- name: Install PostgreSQL
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL and its dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql-13
        - postgresql-contrib
        - postgresql-server-dev-13
        - acl
    - name: Install psycopg2 library
      apt:
        name: python3-psycopg2
        state: present


    - name: Configure pg_hba.conf
      lineinfile:
        path: /etc/postgresql/13/main/pg_hba.conf
        regexp: "^host.*all.*all.*127.0.0.1/32.*md5$"
        line: "host    all             all             0.0.0.0/0               md5"
        state: present
      notify:
        - Restart PostgreSQL

    - name: Configure postgresql.conf
      lineinfile:
        path: /etc/postgresql/13/main/postgresql.conf
        regexp: "^#?listen_addresses.*"
        line: "listen_addresses = '*'"
        state: present
      notify:
        - Restart PostgreSQL

    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data
 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

    - name: Enable passwordless sudo
      lineinfile: dest=/etc/sudoers regexp=^vagrant line="vagrant ALL=(postgres) NOPASSWD:/bin/sh"

    - name: Create a PostgreSQL database user
      postgresql_user: name=admin password=admin role_attr_flags=CREATEDB state=present
      become: yes
      become_user: postgres
      become_method: sudo
    - name: Create people database
      become: yes
      become_user: postgres
      postgresql_db:
        name: people
        encoding: UTF-8

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
