- name: Frontend configuration
  hosts: localhost
  become: true

  tasks:
    - name: Install nginx
      apt: 
        name: nginx

    - name: Install nginx-start
      service: 
        name: nginx
        state: started

    - name: Install Node.js package
      apt:
        name: nodejs
        state: latest

    - name: Install npm package manager
      apt:
        name: npm
        state: latest
    
    - name: Downloading node.js source
      shell: curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs
      tags:
      - nodejs
    
    - name: Install Node.js dependencies
      npm:
        path: /home/tdm137/chmury-w-aplikacjach/frontend

    - name: Build the app
      command: /usr/bin/npm run build
      args:
        chdir: /home/tdm137/chmury-w-aplikacjach/frontend

    - name: Copy frontend files
      copy:
        remote_src: yes
        src: /home/tdm137/chmury-w-aplikacjach/frontend/dist/
        dest: /var/www/html/