- name: Frontend configuration
  hosts: frontend
  become: true

  tasks:
    - name: Install nginx
      apt: 
        name: nginx

    - name: Install nginx-start
      service: 
        name: nginx
        state: started

    - name: Install Node.js package
      apt:
        name: nodejs
        state: latest

    - name: Install npm package manager
      apt:
        name: npm
        state: latest
            
    - name: Install Node.js dependencies
      npm:
        path: /home/vagrant/chmury-w-aplikacjach/frontend

    - name: Build the app
      command: /usr/bin/npm run build
      args:
        chdir: /home/vagrant/chmury-w-aplikacjach/frontend
      environment:
        REACT_APP_API_URL: http://192.168.56.4:5173

    - name: Copy frontend files
      copy:
        remote_src: yes
        src: /home/vagrant/chmury-w-aplikacjach/frontend/
        dest: /var/www/html/