kind create cluster --config=kind-cluster.yml
kind load docker-image backend:1.0
kind load docker-image frontend:1.0
kubectl apply -f database/database-config.yml
kubectl apply -f database/database-pvc-pv.yml
kubectl apply -f database/database-pod.yml
kubectl apply -f database/database-service.yml
kubectl create -f backend/backend-secret.yml
kubectl apply -f backend/backend-pod.yml
kubectl apply -f backend/backend-service.yml
kubectl apply -f frontend/frontend-pod.yml
kubectl apply -f frontend/frontend-service.yml
